// ! DO NOT EDIT THIS FILE ! CREATE 'environment.json' INSTEAD ! //

const PORT = 8080

const MONGO_DB = 'metis'
const MONGO_HOST = 'localhost'
const MONGO_PORT = 27017
const HTTP_RATE_LIMIT = 25
const WS_RATE_LIMIT = 25
const FILE_STORE_DIR = './files/store'

export default {
  PORT,
  MONGO_DB,
  MONGO_HOST,
  MONGO_PORT,
  HTTP_RATE_LIMIT,
  WS_RATE_LIMIT,
  FILE_STORE_DIR,
}
