import type { TMissionImportBuild } from '../MissionImport'

// -- BUILD 18 --
// This migration script is responsible
// for replacing the actionID of actions
// generated by build_000003.js with a
// randomly generated actionID.

const build: TMissionImportBuild = (missionData) => {
  // Grab the nodeData.
  let nodeData = missionData.nodeData

  for (let nodeDatum of nodeData) {
    if (nodeDatum.actions) {
      let actions = nodeDatum.actions

      for (let action of actions) {
        if (action.actionID === 'migration-generated-action') {
          action.actionID = `${Math.random()
            .toString(36)
            .substring(2, 15)}${Math.random().toString(36).substring(2, 15)}`
        }
      }
    }
  }
}

export default build
